FROM anapsix/alpine-java
LABEL maintainer="naresh.bogathi"
COPY /target/enrollment-service-0.0.1-SNAPSHOT.jar /home/enrollment-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","/home/enrollment-service-0.0.1-SNAPSHOT.jar"]